# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:26
from __future__ import unicode_literals

import authapp.submodels.usermanager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authapp.submodels.usermanager.UserManager()),
            ],
        ),
    ]
