# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumtype',
            name='type',
        ),
        migrations.AddField(
            model_name='albumtype',
            name='album_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='albumtype',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
