# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:02
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_minimum_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='album_minimum_price')),
                ('album_minimum_price_difference_visible', models.BooleanField(default=False, verbose_name='album_minimum_price_difference_visible')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='commission_percent')),
                ('commission_charge_visible', models.BooleanField(default=False, verbose_name='commission_charge_visible')),
                ('photographer_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='photographer_charge')),
                ('photographer_charge_visible', models.BooleanField(default=False, verbose_name='photographer_charge_visible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'global_settings',
                'verbose_name_plural': 'global_settings',
            },
        ),
    ]
