# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='album_minimum_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='album_minimum_price_difference_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='commission_charge_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='photographer_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='photographer_charge_visible',
            field=models.BooleanField(default=False),
        ),
    ]
